well_commerce_producer:
    configuration:
        producer:
            orm:
                factory: WellCommerce\Bundle\ProducerBundle\Factory\ProducerFactory
                repository: WellCommerce\Bundle\ProducerBundle\Repository\ProducerRepository
                mapping: "@WellCommerceProducerBundle/Resources/config/doctrine/Producer.orm.yml"
                entity: WellCommerce\Bundle\ProducerBundle\Entity\Producer
            api:
                exposed: true
                dataset: producer.dataset.admin
                manager: producer.manager
            dynamic_routing:
                entity: WellCommerce\Bundle\ProducerBundle\Entity\ProducerRoute
                generator: WellCommerce\Bundle\ProducerBundle\Routing\ProducerRouteGenerator
                defaults:
                    _controller: producer.controller.front:indexAction
                    limit: 12
                    page: 1
                    orderBy: name
                    orderDir: asc
                    priceFrom: 0
                    priceTo: 9999
                    view: grid
                    producers: ~
                    attributes: ~
                requirements:
                    limit: "\\d{1,10}"
                    page: "\\d{1,10}"
                    orderBy: "name|finalPrice"
                    orderDir: "asc|desc"
                    priceFrom: "\\d{1,10}"
                    priceTo: "\\d{1,10}"
                    view: "grid|list"
                    producers: "[\\d+_]+"
                    attributes: "[\\d+_]+"
                pattern: "{page},{limit},{orderBy},{orderDir},{priceFrom},{priceTo},{view},{producers},{attributes}"
        producer_route:
            orm:
                mapping: "@WellCommerceProducerBundle/Resources/config/doctrine/ProducerRoute.orm.yml"
                entity: WellCommerce\Bundle\ProducerBundle\Entity\ProducerRoute
        producer_translation:
            orm:
                manager: false
                mapping: "@WellCommerceProducerBundle/Resources/config/doctrine/ProducerTranslation.orm.yml"
                entity: WellCommerce\Bundle\ProducerBundle\Entity\ProducerTranslation

