# WellCommerce Open-Source E-Commerce Platform
#
# This file is part of the WellCommerce package.
# (c) Adam Piotrowski <adam@wellcommerce.org>
#
# For the full copyright and license information,
# please view the LICENSE file that was distributed with this source code.

doctrine:
    orm:
        resolve_target_entities:
            WellCommerce\Bundle\ProducerBundle\Entity\ProducerInterface: WellCommerce\Bundle\ProducerBundle\Entity\Producer

well_commerce_api:
    request_handler:
        producer:
            manager: producer.manager
    serialization:
        WellCommerce\Bundle\ProducerBundle\Entity\Producer:
            mapping: "@WellCommerceProducerBundle/Resources/config/serialization/Producer.yml"
        WellCommerce\Bundle\ProducerBundle\Entity\ProducerRoute:
            mapping: "@WellCommerceProducerBundle/Resources/config/serialization/ProducerRoute.yml"
        WellCommerce\Bundle\ProducerBundle\Entity\ProducerTranslation:
            mapping: "@WellCommerceProducerBundle/Resources/config/serialization/ProducerTranslation.yml"

well_commerce_locale:
    copier:
        entities:
            WellCommerce\Bundle\ProducerBundle\Entity\ProducerTranslation:
                properties:
                    - name
                    - slug

well_commerce_routing:
    dynamic_routing:
        producer:
            entity: WellCommerce\Bundle\ProducerBundle\Entity\ProducerRoute
            generator: WellCommerce\Bundle\ProducerBundle\Routing\ProducerRouteGenerator
            defaults:
                _controller: producer.controller.front:indexAction
                limit: 12
                page: 1
                orderBy: name
                orderDir: asc
                priceFrom: 0
                priceTo: 9999
                view: grid
                producers: ~
                attributes: ~
            requirements:
                limit: "\\d{1,10}"
                page: "\\d{1,10}"
                orderBy: "name|finalPrice"
                orderDir: "asc|desc"
                priceFrom: "\\d{1,10}"
                priceTo: "\\d{1,10}"
                view: "grid|list"
                producers: "[\\d+_]+"
                attributes: "[\\d+_]+"
            pattern: "{page},{limit},{orderBy},{orderDir},{priceFrom},{priceTo},{view},{producers},{attributes}"
