admin.producer.index:
    path: /admin/catalog/producer/index
    defaults:
        _controller: 'producer.controller.admin:indexAction'
    options:
        require_admin_permission: producer.index
admin.producer.grid:
    path: /admin/catalog/producer/grid
    defaults:
        _controller: 'producer.controller.admin:gridAction'
    options:
        expose: true
        require_admin_permission: producer.index
admin.producer.add:
    path: /admin/catalog/producer/add
    defaults:
        _controller: 'producer.controller.admin:addAction'
    options:
        require_admin_permission: producer.add
admin.producer.edit:
    path: '/admin/catalog/producer/edit/{id}'
    defaults:
        _controller: 'producer.controller.admin:editAction'
    options:
        expose: true
        require_admin_permission: producer.edit
admin.producer.delete:
    path: '/admin/catalog/producer/delete/{id}'
    defaults:
        _controller: 'producer.controller.admin:deleteAction'
    options:
        expose: true
        require_admin_permission: producer.delete
