WellCommerce\Bundle\ProducerBundle\Entity\Producer:
    fields:
        id:
            groups:
                - default
                - producer
    associations:
        photo:
            groups:
                - producer
        deliverers:
            groups:
                - producer
        translations:
            groups:
                - producer
        shops:
            groups:
                - producer
